# 簡訊內容過濾分析

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Code-Gym/python-dataset/master/msg.txt', 
                   sep='\t', 
                   names=['status', 'msg'])
display(df)

     status                                                msg
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## startswith, endswith

In [3]:
df['msg'].str.startswith('a')

0       False
1       False
2       False
3       False
4       False
        ...
5567    False
5568    False
5569    False
5570    False
5571    False
Name: msg, Length: 5572, dtype: bool

In [4]:
df.loc[df['msg'].str.startswith('a')]

     status                                                msg
427     ham                        aathi..where are you dear..
907    spam  all the lastest from Stereophonics, Marley, Di...
1071    ham    alright, I'll make sure the car is back tonight
2088    ham  alright babe, justthought id sayhey! how u do...
2843    ham                        aathi..where are you dear..
2950    ham                at bruce b downs &amp; fletcher now
3440    ham  awesome, how do I deal with the gate? Charles ...
3471    ham                        aathi..where are you dear..
3555    ham                     am up to my eyes in philosophy
4249   spam  accordingly. I repeat, just text the word ok o...
4424    ham  alright. Thanks for the advice. Enjoy your nig...
4881    ham  alright tyler's got a minor crisis and has to ...
5448    ham  aight we can pick some up, you open before ton...

In [5]:
df[df['msg'].str.startswith('a')]

     status                                                msg
427     ham                        aathi..where are you dear..
907    spam  all the lastest from Stereophonics, Marley, Di...
1071    ham    alright, I'll make sure the car is back tonight
2088    ham  alright babe, justthought id sayhey! how u do...
2843    ham                        aathi..where are you dear..
2950    ham                at bruce b downs &amp; fletcher now
3440    ham  awesome, how do I deal with the gate? Charles ...
3471    ham                        aathi..where are you dear..
3555    ham                     am up to my eyes in philosophy
4249   spam  accordingly. I repeat, just text the word ok o...
4424    ham  alright. Thanks for the advice. Enjoy your nig...
4881    ham  alright tyler's got a minor crisis and has to ...
5448    ham  aight we can pick some up, you open before ton...

## 過濾不是垃圾信的訊息

In [6]:
ham_df = df[df['status'] == 'ham']

## 過濾不是垃圾信的訊息中，包含英文單字「OK」的訊息
contains( )

In [7]:
mask = df['msg'].str.contains('OK')
mask

0       False
1       False
2       False
3       False
4       False
        ...
5567    False
5568    False
5569    False
5570    False
5571    False
Name: msg, Length: 5572, dtype: bool

In [8]:
df[mask]

     status                                                msg
225    spam  500 New Mobiles from 2004, MUST GO! Txt: NOKIA...
457     ham  LOOK AT AMY URE A BEAUTIFUL, INTELLIGENT WOMAN...
803    spam  FREE for 1st week! No1 Nokia tone 4 ur mobile ...
820     ham  BOO BABE! U ENJOYIN YOURJOB? U SEEMED 2 B GETT...
984     ham  LOOK AT THE FUCKIN TIME. WHAT THE FUCK YOU THI...
1017   spam  FREE for 1st week! No1 Nokia tone 4 ur mob eve...
1048   spam  1000's flirting NOW! Txt GIRL or BLOKE & ur NA...
1080    ham  Me too watching surya movie only. . .after 6 p...
1207   spam  As a SIM subscriber, you are selected to recei...
1221   spam  No. 1 Nokia Tone 4 ur mob every week! Just txt...
1303    ham  FRAN I DECIDED 2 GO N E WAY IM COMPLETELY BROK...
1375   spam  500 New Mobiles from 2004, MUST GO! Txt: NOKIA...
1380   spam  No. 1 Nokia Tone 4 ur mob every week! Just txt...
1574   spam  SMS AUCTION - A BRAND NEW Nokia 7250 is up 4 a...
1765   spam  Hi 07734396839 IBH Customer Loyalty Offer: The...
1848   spam  FREE NOKIA Or Motorola with upto 12mths 1/2pri...
1908    ham                                    ELLO BABE U OK?
2074   spam  FreeMsg: Claim ur 250 SMS messages-Text OK to ...
2158    ham  Sad story of a Man - Last week was my b'day. M...
2160   spam  FREE for 1st week! No1 Nokia tone 4 ur mob eve...
2217    ham  OK i'm waliking ard now... Do u wan me 2 buy a...
2360   spam  Spook up your mob with a Halloween collection ...
2480   spam  Sppok up ur mob with a Halloween collection of...
2514   spam  U have won a nokia 6230 plus a free digital ca...
2606    ham  HELLO U.CALL WEN U FINISH WRK.I FANCY MEETIN U...
2664   spam  8007 FREE for 1st week! No1 Nokia tone 4 ur mo...
2849    ham  Sad story of a Man - Last week was my b'day. M...
3126   spam  1st wk FREE! Gr8 tones str8 2 u each wk. Txt N...
3149    ham  CHEERS U TEX MECAUSE U WEREBORED! YEAH OKDEN H...
3186    ham  MAYBE IF YOU WOKE UP BEFORE FUCKING 3 THIS WOU...
3211    ham  She said,'' do u mind if I go into the bedroom...
3212    ham  OH YEAH,AND HAV A GREAT TIME IN NEWQUAY-SEND M...
3324    ham  She said,'' do u mind if I go into the bedroom...
3585   spam  Hi 07734396839 IBH Customer Loyalty Offer: The...
3644    ham  Sorry, left phone upstairs. OK, might be hecti...
3763   spam  FREE for 1st week! No1 Nokia tone 4 ur mob eve...
3980    ham  CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...
4198   spam  FREE for 1st week! No1 Nokia tone 4 ur mob eve...
4358    ham  HELLOGORGEOUS, HOWS U? MY FONE WAS ON CHARGE L...
4468    ham  She said,'' do u mind if I go into the bedroom...
4834   spam  New Mobiles from 2004, MUST GO! Txt: NOKIA to ...
4994    ham  HEY KATE, HOPE UR OK... WILL GIVE U A BUZ WEDL...
5141   spam  FREE for 1st week! No1 Nokia tone 4 ur mobile ...
5155    ham  MY NEW YEARS EVE WAS OK. I WENT TO A PARTY WIT...
5178   spam  SMS AUCTION - A BRAND NEW Nokia 7250 is up 4 a...
5196   spam  Spook up your mob with a Halloween collection ...
5202    ham           WOT STUDENT DISCOUNT CAN U GET ON BOOKS?
5224    ham  OH FUCK. JUSWOKE UP IN A BED ON A BOATIN THE D...

## 處理欄位名稱
將欄位名稱改為大寫

In [9]:
df.columns.str.upper()

Index(['STATUS', 'MSG'], dtype='object')

In [10]:
df.columns = df.columns.str.upper()
display(df)

     STATUS                                                MSG
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## 課後練習解答

In [12]:
mask1 = df['MSG'].str.startswith('L')
df[mask & mask1]

    STATUS                                                MSG
457    ham  LOOK AT AMY URE A BEAUTIFUL, INTELLIGENT WOMAN...
984    ham  LOOK AT THE FUCKIN TIME. WHAT THE FUCK YOU THI...