# Google 股價為範例，操作時間序列的技巧

In [5]:
import pandas as pd
import datetime as dt
import pandas_datareader.data as data

start = dt.datetime(2021, 11, 1)
end = dt.datetime(2021, 12, 19)
df = data.get_data_yahoo('GOOG', start, end)
display(df)

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2021-11-01,2967.989990,2871.590088,2963.300049,2875.479980,1613600,2875.479980
2021-11-02,2938.409912,2892.820068,2896.187988,2917.260010,1057500,2917.260010
2021-11-03,2938.209961,2901.070068,2925.500000,2935.800049,894300,2935.800049
2021-11-04,2999.000000,2932.699951,2944.000000,2973.659912,1235000,2973.659912
2021-11-05,3011.415039,2973.040039,2987.070068,2984.820068,1019700,2984.820068
2021-11-08,3020.689941,2982.399902,3000.000000,2987.030029,919400,2987.030029
2021-11-09,3007.570068,2950.139893,2994.919922,2984.969971,843800,2984.969971
2021-11-10,2974.000000,2906.500000,2960.195068,2932.520020,1135400,2932.520020
2021-11-11,2970.044922,2933.889893,2942.139893,2934.959961,623200,2934.959961
2021-11-12,2997.189941,2929.080078,2956.629883,2992.909912,852000,2992.909912
2021-11-15,3009.540039,2973.050049,3000.000000,2987.760010,812400,2987.760010
2021-11-16,2996.649902,2967.000000,2983.409912,2981.520020,862700,2981.520020
2021-11-17,2992.520020,2971.260010,2984.580078,2981.239990,764500,2981.239990
2021-11-18,3032.199951,2979.969971,2982.919922,3014.179932,1332900,3014.179932
2021-11-19,3037.000000,2997.750000,3020.000000,2999.050049,988300,2999.050049
2021-11-22,3014.889893,2940.110107,3002.834961,2941.570068,1230400,2941.570068
2021-11-23,2953.879883,2897.790039,2942.260010,2935.139893,906300,2935.139893
2021-11-24,2940.000000,2903.979980,2927.000000,2934.350098,823200,2934.350098
2021-11-26,2905.939941,2849.709961,2900.310059,2856.120117,849600,2856.120117
2021-11-29,2937.239990,2885.969971,2885.969971,2922.280029,1313800,2922.280029
2021-11-30,2932.570068,2841.320068,2909.004883,2849.040039,2079500,2849.040039
2021-12-01,2929.982910,2830.000000,2884.250000,2832.360107,1423800,2832.360107
2021-12-02,2893.500000,2819.639893,2836.479980,2875.530029,1062500,2875.530029
2021-12-03,2904.260010,2823.000000,2889.909912,2850.409912,1333800,2850.409912
2021-12-06,2887.030029,2812.939941,2871.479980,2875.929932,1109900,2875.929932
2021-12-07,2966.000000,2914.050049,2919.000000,2960.729980,1162900,2960.729980
2021-12-08,2983.129883,2944.000000,2966.629883,2974.409912,948200,2974.409912
2021-12-09,2992.100098,2950.580078,2963.520020,2962.120117,929000,2962.120117
2021-12-10,2988.000000,2947.149902,2982.000000,2973.500000,1081700,2973.500000
2021-12-13,2971.250000,2927.199951,2968.879883,2934.090088,1205200,2934.090088
2021-12-14,2908.840088,2844.850098,2895.399902,2899.409912,1238900,2899.409912
2021-12-15,2950.344971,2854.110107,2887.320068,2947.370117,1364000,2947.370117
2021-12-16,2971.030029,2881.850098,2961.540039,2896.770020,1370000,2896.770020
2021-12-17,2889.201904,2835.760010,2854.290039,2856.060059,2162800,2856.060059

## DatetimeIndex
用時間作為索引的型態<br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html

In [6]:
df.index.week

<ipython-input-6-1397a0ba33b2>:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  df.index.week

Int64Index([44, 44, 44, 44, 44, 45, 45, 45, 45, 45, 46, 46, 46, 46, 46, 47, 47,
            47, 47, 48, 48, 48, 48, 48, 49, 49, 49, 49, 49, 50, 50, 50, 50,
            50],
           dtype='int64', name='Date')

## 計算每週交易量總和

In [7]:
df['week'] = df.index.week
df

<ipython-input-7-fcd2fc349e0e>:1: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series.  To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  df['week'] = df.index.week

,High,Low,Open,Close,Volume,Adj Close,week
Date,,,,,,,
2021-11-01,2967.989990,2871.590088,2963.300049,2875.479980,1613600,2875.479980,44
2021-11-02,2938.409912,2892.820068,2896.187988,2917.260010,1057500,2917.260010,44
2021-11-03,2938.209961,2901.070068,2925.500000,2935.800049,894300,2935.800049,44
2021-11-04,2999.000000,2932.699951,2944.000000,2973.659912,1235000,2973.659912,44
2021-11-05,3011.415039,2973.040039,2987.070068,2984.820068,1019700,2984.820068,44
2021-11-08,3020.689941,2982.399902,3000.000000,2987.030029,919400,2987.030029,45
2021-11-09,3007.570068,2950.139893,2994.919922,2984.969971,843800,2984.969971,45
2021-11-10,2974.000000,2906.500000,2960.195068,2932.520020,1135400,2932.520020,45
2021-11-11,2970.044922,2933.889893,2942.139893,2934.959961,623200,2934.959961,45
2021-11-12,2997.189941,2929.080078,2956.629883,2992.909912,852000,2992.909912,45
2021-11-15,3009.540039,2973.050049,3000.000000,2987.760010,812400,2987.760010,46
2021-11-16,2996.649902,2967.000000,2983.409912,2981.520020,862700,2981.520020,46
2021-11-17,2992.520020,2971.260010,2984.580078,2981.239990,764500,2981.239990,46
2021-11-18,3032.199951,2979.969971,2982.919922,3014.179932,1332900,3014.179932,46
2021-11-19,3037.000000,2997.750000,3020.000000,2999.050049,988300,2999.050049,46
2021-11-22,3014.889893,2940.110107,3002.834961,2941.570068,1230400,2941.570068,47
2021-11-23,2953.879883,2897.790039,2942.260010,2935.139893,906300,2935.139893,47
2021-11-24,2940.000000,2903.979980,2927.000000,2934.350098,823200,2934.350098,47
2021-11-26,2905.939941,2849.709961,2900.310059,2856.120117,849600,2856.120117,47
2021-11-29,2937.239990,2885.969971,2885.969971,2922.280029,1313800,2922.280029,48
2021-11-30,2932.570068,2841.320068,2909.004883,2849.040039,2079500,2849.040039,48
2021-12-01,2929.982910,2830.000000,2884.250000,2832.360107,1423800,2832.360107,48
2021-12-02,2893.500000,2819.639893,2836.479980,2875.530029,1062500,2875.530029,48
2021-12-03,2904.260010,2823.000000,2889.909912,2850.409912,1333800,2850.409912,48
2021-12-06,2887.030029,2812.939941,2871.479980,2875.929932,1109900,2875.929932,49
2021-12-07,2966.000000,2914.050049,2919.000000,2960.729980,1162900,2960.729980,49
2021-12-08,2983.129883,2944.000000,2966.629883,2974.409912,948200,2974.409912,49
2021-12-09,2992.100098,2950.580078,2963.520020,2962.120117,929000,2962.120117,49
2021-12-10,2988.000000,2947.149902,2982.000000,2973.500000,1081700,2973.500000,49
2021-12-13,2971.250000,2927.199951,2968.879883,2934.090088,1205200,2934.090088,50
2021-12-14,2908.840088,2844.850098,2895.399902,2899.409912,1238900,2899.409912,50
2021-12-15,2950.344971,2854.110107,2887.320068,2947.370117,1364000,2947.370117,50
2021-12-16,2971.030029,2881.850098,2961.540039,2896.770020,1370000,2896.770020,50
2021-12-17,2889.201904,2835.760010,2854.290039,2856.060059,2162800,2856.060059,50

In [8]:
df.groupby('week').Volume.sum()

week
44    5820100
45    4373800
46    4760800
47    3809500
48    7213400
49    5231700
50    7340900
Name: Volume, dtype: int64

## resample
調整週期重新採樣的方法<br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html#pandas.DataFrame.resample

In [9]:
ten = df.resample('10D').mean()
ten

,High,Low,Open,Close,Volume,Adj Close,week
Date,,,,,,,
2021-11-01,2982.160614,2926.282501,2958.896637,2948.942505,1.089838e+06,2948.942505,44.375000
2021-11-11,3005.020682,2964.571429,2981.382812,2984.517125,8.908571e+05,2984.517125,45.714286
2021-11-21,2947.419963,2886.480021,2927.896647,2906.416707,1.200467e+06,2906.416707,47.333333
2021-12-01,2943.000366,2880.169983,2914.158722,2913.123749,1.131475e+06,2913.123749,48.625000
2021-12-11,2938.133398,2868.754053,2913.485986,2906.740039,1.468180e+06,2906.740039,50.000000